; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Velocità della seriale
monitor_speed = 115200

; CORREZIONE: Forziamo PlatformIO a scaricare i pacchetti via Git/HTTPS diretto
; per ignorare il blocco del modulo SSL di macOS
lib_deps =
    wollewald/INA226_WE @ ^1.3.0
    milesburton/DallasTemperature @ ^3.11.0
    paulstoffregen/OneWire @ ^2.3.8
    bblanchon/ArduinoJson @ ^7.0.0
    links2004/WebSockets @ ^2.4.1

; Ottimizzazione della memoria flash e LittleFS per i tuoi file web
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv

[env:esp32dev_2ch_outlet]
extends = env:esp32dev
build_flags = -DDISABLE_LIGHT

[env:esp32dev_4ch_light]
extends = env:esp32dev
build_flags = -DCHANNELS_4

[env:esp32dev_4ch_outlet]
extends = env:esp32dev
build_flags = -DCHANNELS_4 -DDISABLE_LIGHT